Inscription api
FEMMLille/findYourTrashCan pull request #11
Opened 2017-11-07 16:58 UTC by Darkshad

Mise en place de l'inscription

Github #2  #10  #9

2017-11-08 09:15 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/controller/FYTCUserController.java
> +		logger.info("WebService createUser [username : "+ user.getUsername() +", password : "+ user.getPassword() +", mail : "+ user.getEmail() +"]");
Formater le code pour avoir des espace entre les "+" (ctrl + shift + f)
cf bonne pratique

2017-11-08 09:33 UTC, ExSoldat commented on findyourtrashcan-api/src/main/resources/application-prod.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/fytcProd?useSSL=true
C'est pas un petit peu dangereux de push ces modifications ? Elles ne devraient pas être dans les fichiers qui ne seront jamais modifiés ?

2017-11-08 09:33 UTC, ExSoldat commented on findyourtrashcan-api/src/test/java/fr/femm/findyourtrashcan/controller/FYTCUserControllerTest.java
> +    /*
Cette partie, on peut la supprimer non ?

2017-11-08 09:57 UTC, MawsFr requested changes
Ajouter des commentaires sur les classes en général, sur leur attribut (pas les getters et setters)

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/controller/FYTCUserController.java
> +		logger.info("WebService createUser [username : "+ user.getUsername() +", password : "+ user.getPassword() +", mail : "+ user.getEmail() +"]");
Formater le code pour avoir des espace entre les "+" (ctrl + shift + f)
cf bonne pratique

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/data/FYTCUser.java
> +		this.role = "USER";
Peut être faire une classe ?

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/controller/FYTCUserController.java
>  	@RequestMapping(method=RequestMethod.POST)
Utiliser PostMapping de spring mvc

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/DataSourceConfig.java
> +	@Bean(name="dataSource")
Constante

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/DataSourceConfig.java
> +	    driverManagerDataSource.setDriverClassName("org.postgresql.Driver");
Constante

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/DataSourceConfig.java
> +	@Value("${spring.datasource.url}")
Constante

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/TokenAuthenticationService.java
> +	static final String SECRET = "ThisIsASecret";
ajouter public

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/WebSecurityConfig.java
> +	        	.antMatchers(HttpMethod.POST, "/api/user").permitAll()
constantes

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/WebSecurityConfig.java
> +	        .addFilterBefore(new JWTLoginFilter("/api/login", authenticationManager()),
constantes

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/WebSecurityConfig.java
> +		.usersByUsernameQuery("SELECT username, password,enabled FROM fytcuser WHERE username=?")
constantes

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/WebSecurityConfig.java
> +		.authoritiesByUsernameQuery("SELECT username" + ", role FROM fytcuser WHERE username=?");
constantes

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/main/resources/application-int.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
Ne pas droper la base mais laisse le choix au deploy -> modifier le job jenkins
-> pour le moment mettre update

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/test/java/fr/femm/findyourtrashcan/controller/FYTCUserControllerTest.java
> +        mockMvc.perform(post("http://localhost:8080/api/user")
constantes on sais jamais le port change non ?

2017-11-08 09:57 UTC, MawsFr commented on findyourtrashcan-api/src/test/java/fr/femm/findyourtrashcan/service/FYTCUserServiceTest.java
> +		FYTCUser userToTest = new FYTCUser("maws", "bg", "wo@gmail.com");
formater le code ctrl  shift f

2017-11-08 10:00 UTC, MawsFr commented on findyourtrashcan-api/src/test/java/fr/femm/findyourtrashcan/controller/FYTCUserControllerTest.java
> +    /*
oui

2017-11-08 10:33 UTC, Darkshad commented on findyourtrashcan-api/src/test/java/fr/femm/findyourtrashcan/controller/FYTCUserControllerTest.java
> +    /*
Euh j'avais mis en commentaire car j'avais besoin d'un template pour ça mais ouais je vais le mettre de coté

2017-11-08 12:46 UTC, Darkshad commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/controller/FYTCUserController.java
> +		logger.info("WebService createUser [username : "+ user.getUsername() +", password : "+ user.getPassword() +", mail : "+ user.getEmail() +"]");
oui

2017-11-08 12:47 UTC, Darkshad commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/data/FYTCUser.java
> +		this.role = "USER";
Bah je rajoute en tache trello,a voir pour après

2017-11-08 12:52 UTC, Darkshad commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/security/TokenAuthenticationService.java
> +	static final String SECRET = "ThisIsASecret";
Je pense que c'est pas public exprès car c'est un truc interne

2017-11-08 12:52 UTC, Darkshad commented on findyourtrashcan-api/src/main/resources/application-int.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
ok

2017-11-08 12:55 UTC, Darkshad commented on findyourtrashcan-api/src/test/java/fr/femm/findyourtrashcan/controller/FYTCUserControllerTest.java
> +        mockMvc.perform(post("http://localhost:8080/api/user")
Ouais pk pas

2017-11-15 11:16 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/controller/FYTCUserController.java
> +		logger.info("WebService createUser [username : "+ user.getUsername() +", password : "+ user.getPassword() +", mail : "+ user.getEmail() +"]");
Et ils sont où mes espaces xD ?

2017-11-15 11:17 UTC, MawsFr commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/data/FYTCUser.java
> +		this.role = "USER";
Une classe bordel xD

2017-11-16 17:17 UTC, Darkshad commented on findyourtrashcan-api/src/main/java/fr/femm/findyourtrashcan/controller/FYTCUserController.java
> +		logger.info("WebService createUser [username : "+ user.getUsername() +", password : "+ user.getPassword() +", mail : "+ user.getEmail() +"]");
Ah mince,pensait l'avoir fait

2017-11-17 23:57 UTC, MawsFr approved these changes

2017-11-17 23:57 UTC, merged